shop/config/routes.rb
Rails.application.routes.draw do
  resources :parts

end

shop/app/models/part.rb
class Part < ActiveRecord::Base
end

shop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

shop/app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:number, :name, :typ, :description)
    end
end

shop/app/helpers/application_helper.rb
module ApplicationHelper
end

shop/app/helpers/parts_helper.rb
module PartsHelper
end

shop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1> Hyper-Mega-Onlineshop </h1>
<br>
<br>

<%= yield %>

</body>
</html>

shop/app/views/parts/_form.html.erb
<%= form_for(@part) do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% @part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :typ %><br>
    <%= f.text_field :typ %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

shop/app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render 'form' %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

shop/app/views/parts/index.html.erb
<h1>Artikel</h1>

<table>
  <thead>
    <tr>
      <th>Artikelnumber</th>
      <th>Artikelname</th>
      <th>Artikeltyp</th>
      <th>Artikelbeschreibung</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.number %></td>
        <td><%= part.name %></td>
        <td><%= part.typ %></td>
        <td><%= part.description %></td>
        <td><%= link_to 'Show', part %></td>
        <td><%= link_to 'Edit', edit_part_path(part) %></td>
        <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Artikel anlegen', new_part_path %>

shop/app/views/parts/new.html.erb
<h1>Neuer Artikel</h1>

<%= render 'form' %>

<%= link_to 'Back', parts_path %>

shop/app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @part.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @part.name %>
</p>

<p>
  <strong>Typ:</strong>
  <%= @part.typ %>
</p>

<p>
  <strong>Description:</strong>
  <%= @part.description %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>